import { supabase } from '../lib/supabase'
import type { Transaction, TransactionType } from '../lib/types'

export type TransactionInput = {
  account_id: string
  category_id: string | null
  type: TransactionType
  amount: number
  date: string
  description: string
  notes: string | null
  tags: string[]
  transfer_to_account_id: string | null
}

const PAGE = 1000

export type ListTransactionsFilter = {
  from?: string
  to?: string
  accountId?: string
}

export async function listTransactions(
  filter: ListTransactionsFilter = {},
): Promise<Transaction[]> {
  const all: Transaction[] = []
  let offset = 0
  while (true) {
    let q = supabase
      .from('transactions')
      .select('*')
      .order('date', { ascending: false })
      .range(offset, offset + PAGE - 1)
    if (filter.from) q = q.gte('date', filter.from)
    if (filter.to) q = q.lte('date', filter.to)
    if (filter.accountId) {
      q = q.or(`account_id.eq.${filter.accountId},transfer_to_account_id.eq.${filter.accountId}`)
    }
    const { data, error } = await q
    if (error) throw new Error(error.message)
    all.push(...(data as Transaction[]))
    if (data.length < PAGE) break
    offset += PAGE
  }
  return all
}

export async function createTransaction(input: TransactionInput): Promise<void> {
  const { error } = await supabase.from('transactions').insert(input)
  if (error) throw new Error(error.message)
}

const INSERT_CHUNK = 500

/**
 * Batch insert (spreadsheet import). Inserts in chunks; on failure throws
 * with the number of rows already inserted so the caller can report a
 * partial import instead of silently losing data.
 */
export async function createTransactions(inputs: TransactionInput[]): Promise<void> {
  for (let i = 0; i < inputs.length; i += INSERT_CHUNK) {
    const { error } = await supabase.from('transactions').insert(inputs.slice(i, i + INSERT_CHUNK))
    if (error) throw new Error(`${error.message} (${i} of ${inputs.length} rows inserted)`)
  }
}

export async function updateTransaction(id: string, input: TransactionInput): Promise<void> {
  const { error } = await supabase.from('transactions').update(input).eq('id', id)
  if (error) throw new Error(error.message)
}

export async function deleteTransaction(id: string): Promise<void> {
  const { error } = await supabase.from('transactions').delete().eq('id', id)
  if (error) throw new Error(error.message)
}

/** Deletes all future transactions generated by a recurring rule (date >= fromDate). */
export async function deleteRecurringFutureTransactions(
  ruleId: string,
  fromDate: string,
): Promise<void> {
  const { error } = await supabase
    .from('transactions')
    .delete()
    .eq('recurring_rule_id', ruleId)
    .gte('date', fromDate)
  if (error) throw new Error(error.message)
}
